bgg_id:
  - 18291 # unpublished-prototype
  - 21804 # traditional-card-games
  - 23953 # outside-scope-bgg
  - 5985 # miscellaneous-game-accessory
  - 18785 # miscellaneous-game-magazine
  - 22427 # miscellaneous-game-book
  - 76085 # unauthorized-production
  - 33456 # miscellaneous-card-game-accessory
  - 96628 # miscellaneous-game-compilation
  - 22104 # miscellaneous-game-merchandise
  - 158003 # miscellaneous-game-patent
  - 31693 # miscellaneous-miniatures-game-accessory
  - 81913 # unidentified-game
bgg_user_name: []
