# Generated by Django 2.1.2 on 2018-10-22 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('bgg_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('min_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_players', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_players_rec', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_players_rec', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_players_best', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_players_best', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_age_rec', models.FloatField(blank=True, null=True)),
                ('max_age_rec', models.FloatField(blank=True, null=True)),
                ('min_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_time', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cooperative', models.BooleanField(default=False)),
                ('compilation', models.BooleanField(default=False)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('num_votes', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('stddev_rating', models.FloatField(blank=True, null=True)),
                ('bayes_rating', models.FloatField(blank=True, null=True)),
                ('complexity', models.FloatField(blank=True, null=True)),
                ('language_dependency', models.FloatField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='artist_for', to='games.Person'),
        ),
        migrations.AddField(
            model_name='game',
            name='designer',
            field=models.ManyToManyField(blank=True, related_name='designer_for', to='games.Person'),
        ),
        migrations.AddField(
            model_name='game',
            name='implementation',
            field=models.ManyToManyField(blank=True, null=True, related_name='implemented_by', to='games.Game'),
        ),
    ]
