# Generated by Django 2.1.4 on 2018-12-07 12:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, db_index=True, null=True)),
                ('owned', models.BooleanField(db_index=True, default=False)),
                ('prev_owned', models.BooleanField(db_index=True, default=False)),
                ('for_trade', models.BooleanField(db_index=True, default=False)),
                ('want_in_trade', models.BooleanField(db_index=True, default=False)),
                ('want_to_play', models.BooleanField(db_index=True, default=False)),
                ('want_to_buy', models.BooleanField(db_index=True, default=False)),
                ('preordered', models.BooleanField(db_index=True, default=False)),
                ('wishlist', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('play_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('rec_rank', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('rec_rating', models.FloatField(blank=True, db_index=True, null=True)),
                ('rec_stars', models.FloatField(blank=True, db_index=True, null=True)),
                ('scraped_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('games', models.ManyToManyField(blank=True, through='games.Collection', to='games.Game')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.User'),
        ),
    ]
