# Generated by Django 2.1.2 on 2018-10-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='implementation',
            field=models.ManyToManyField(blank=True, related_name='implemented_by', to='games.Game'),
        ),
    ]
