# Generated by Django 2.1.4 on 2018-12-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20181207_1256'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('game', 'user')},
        ),
    ]
