# Generated by Django 2.1.2 on 2018-10-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20181022_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-rec_rating', '-bayes_rating')},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='rank',
            new_name='bgg_rank',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='implementation',
            new_name='implementation_of',
        ),
        migrations.AddField(
            model_name='game',
            name='rec_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rec_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='artist_of', to='games.Person'),
        ),
        migrations.AlterField(
            model_name='game',
            name='designer',
            field=models.ManyToManyField(blank=True, related_name='designer_of', to='games.Person'),
        ),
    ]
