# Generated by Django 2.1.3 on 2018-11-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20181106_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-rec_rating', '-bayes_rating', '-avg_rating')},
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='games_game_rec_rat_c0bab3_idx',
        ),
        migrations.AddField(
            model_name='game',
            name='rec_stars',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-rec_rating', '-bayes_rating', '-avg_rating'], name='games_game_rec_rat_3cf101_idx'),
        ),
    ]
