# Generated by Django 2.1.3 on 2018-11-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20181113_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='implementation_of',
            new_name='implements',
        ),
    ]
